all: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10

p1: a2_p1.c
	gcc -Wall -o p1 a2_p1.c

p2: a2_p2.c
	gcc -Wall -o p2 a2_p2.c

p3: a2_p3.c
	gcc -Wall -o p3 a2_p3.c

p4: a2_p4.cpp
	gcc -Wall -o p4 a2_p4.c

p5: a2_p5.c
	gcc -Wall -o p5 a2_p5.c

p6: a2_p6.c
	gcc -Wall -o p6 a2_p6.c

p7: a2_p7.c
	gcc -Wall -o p7 a2_p7.c

p8: a2_p8.cpp
	gcc -Wall -o p8 a2_p8.c

p9: a2_p9.c
	gcc -Wall -o p9 a2_p9.c

p6: a2_p10.c
	gcc -Wall -o p10 a2_p10.c
