all: p1 p2 p3 p4 p5 p6 p7 p8 p9

p1: a9_p1.cpp
	g++ -Wall -o p1 a9_p1.cpp

p2: a9_p2.cpp
	g++ -Wall -o p2 a1_p2.cpp

p3: a9_p3.cpp
	g++ -Wall -o p3 a9_p3.cpp

p4: a9_p4.cpp
	g++ -Wall -o p4 a9_p4.cpp

p5: Guessing_game.cpp
	g++ -Wall -o p5 Guessing_game.cpp

p6: a9_p6.cpp
	g++ -Wall -o p6 a9_p6.cpp
  
p7: a9_p7.cpp
	g++ -Wall -o p7 a9_p7.cpp

p8: a9_p8.cpp
	g++ -Wall -o p8 a9_p8.cpp

p9: a9_p9.cpp
	g++ -Wall -o p9 a9_p9.cpp
