all: p1 p2 p3 p4 p5 p6 p7

p1: cd a12_p1 && echo "In question 1" && \
	g++ -Wall -o p1 Shapes.h Shapes.cpp testHexagon.cpp

p2: cd a12_p2 && echo "In question 2" && \
	g++ -Wall -o p2 TournamentMember.h TournamentMember.cpp testTournamentMember.cpp

p3: cd a12_p3 && echo "In question 3" && \
	g++ -Wall -o p3 TournamentMember.h TournamentMember.cpp testPlayer.cpp

p4: cd a12_p4 && echo "In question 4" && \
	g++ -Wall -o p4 fraction.h fraction.cpp testfraction.cpp

p5: cd a12_p5 && echo "In question 5" && \
	g++ -Wall -o p5 fraction.h fraction.cpp testfraction.cpp

p6: cd a12_p6 && echo "In question 6" && \
	g++ -Wall -o p6 Area.h Circle.h Rectangle.h Square.h Ring.h Area.cpp Circle.cpp Rectangle.cpp Square.cpp Ring.cpp testvirtual.cpp

p7: cd a12_p7 && echo "In question 7" && \
	g++ -Wall -o p7 Area.h Circle.h Rectangle.h Square.h Ring.h Area.cpp Circle.cpp Rectangle.cpp Square.cpp Ring.cpp testvirtual.cpp
