all: p1 p2 p3 p4 p5 p6

p1: a1_p1.c
	gcc -Wall -o p1 a1_p1.c

p2: a1_p2.c
	gcc -Wall -o p2 a1_p2.c

p3: a1_p3.c
	gcc -Wall -o p3 a1_p3.c

p4: a1_p4.cpp
	gcc -Wall -o p4 a1_p4.c

p5: a1_p5.c
	gcc -Wall -o p5 a1_p5.c

p6: a1_p6.c
	gcc -Wall -o p6 a1_p6.c
