all: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12

p1: a4_p1.c
	gcc -Wall -o p1 a4_p1.c

p2: a4_p2.c
	gcc -Wall -o p2 a4_p2.c

p3: a4_p3.c
	gcc -Wall -o p3 a4_p3.c

p4: a4_p4.cpp
	gcc -Wall -o p4 a4_p4.c

p5: a4_p5.c
	gcc -Wall -o p5 a4_p5.c

p6: a4_p6.c
	gcc -Wall -o p6 a4_p6.c

p7: a4_p7.c
	gcc -Wall -o p7 a4_p7.c

p8: a4_p8.cpp
	gcc -Wall -o p8 a4_p8.c

p9: a4_p9.c
	gcc -Wall -o p9 a4_p9.c

p6: a4_p10.c
	gcc -Wall -o p10 a4_p10.c

p6: a4_p11.c
	gcc -Wall -o p11 a4_p11.c

p6: a4_p12.c
	gcc -Wall -o p12 a4_p12.c
