all: p1 p2 p3 p4 p5 p6 p7 p8

p1: a13_p1.cpp
	g++ -Wall -o p1 a9_p1.cpp

p2: cd a13_p2 && echo "In question 2" && \
	g++ -Wall -o p2 Complex.h Complex.cpp testcomplex.cpp

p3: a13_p3.cpp
	g++ -Wall -o p3 a9_p3.cpp

p4: a13_p4.cpp
	g++ -Wall -o p4 a9_p4.cpp

p5: a13_p5.cpp
	g++ -Wall -o p5 a13_p5.cpp

p6: a13_p6.cpp
	g++ -Wall -o p6 a13_p6.cpp
  
p7: a13_p7.cpp
	g++ -Wall -o p7 a13_p7.cpp

p8: a13_p8.cpp
	g++ -Wall -o p8 a13_p8.cpp
