all: p1 p2 p3 p4 p5 p6

p1: stack.h stack.c teststack.c
	gcc -Wall -o p1 stack.h stack.c teststack.c

p2: a7_p2.c
	gcc -Wall -o p2 a7_p2.c

p3: linked_list.h linked_list.c use_linked_list.c 
	gcc -Wall -o p3 linked_list.h linked_list.c use_linked_list.c 

p4: a7_p4.cpp
	gcc -Wall -o p4 a7_p4.c

p5: a7_p5.c
	gcc -Wall -o p5 a7_p5.c

p6: a7_p6.c
	gcc -Wall -o p6 a7_p6.c
