all: p1 p2 p3 p4 p5 p6 p7 p8 p9

p1: a6_p1.c
	gcc -Wall -o p1 a6_p1.c

p2: a6_p2.c
	gcc -Wall -o p2 a6_p2.c

p3: a6_p3.c
	gcc -Wall -o p3 a6_p3.c

p4: a6_p4.cpp
	gcc -Wall -o p4 a6_p4.c

p5: a6_p5.c
	gcc -Wall -o p5 a6_p5.c

p6: a6_p6.c
	gcc -Wall -o p6 a6_p6.c

p7: a6_p7.c
	gcc -Wall -o p7 a6_p7.c

p8: a6_p8.cpp
	gcc -Wall -o p8 a6_p8.c

p9: a6_p9.c
	gcc -Wall -o p9 a6_p9.c
