all: p1 p2 p3 p4 p5 p6 p7 p8 p9

p1: Critter.h Critter.cpp testcritter.cpp
	g++ -Wall -o p1 Critter.h Critter.cpp testcritter.cpp

p2: a10_p2.cpp
	g++ -Wall -o p2 a10_p2.cpp

p3: City.h City.cpp testcity.cpp
	g++ -Wall -o p3 City.h City.cpp testcity.cpp

p4: cd a10_p4 && echo "In question 4" && \
	g++ -Wall -o p4 Critter.h Critter.cpp testcritter.cpp

p5: cd a10_p5 && echo "In question 5" && \
	g++ -Wall -o p5 Critter.h Critter.cpp testcritter.cpp

p6: cd a10_p6 && echo "In question 6" && \
	g++ -Wall -o p6 Critter.h Critter.cpp testcritter.cpp
  
p7: copyconstructor.cpp
	g++ -Wall -o p7 copyconstructor.cpp

p8: Complex.h Complex.cpp testcomplex.cpp
	g++ -Wall -o p8 a9_p8.cpp

p9: a9_p9.cpp
	g++ -Wall -o p9 a9_p9.cpp
